sudo: required
dist: trusty

language: node_js
node_js:
- 6.1.0

cache:
  directories:
  - node_modules

before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb

before_script:
- gulp build

script: karma start karma.conf.js --single-run

deploy:
  provider: heroku
  buildpack: https://github.com/appstack/heroku-buildpack-nodejs-gulp.git
  api_key:
    secure: GfJ/v0uvsK0muDef5ZN1kZap5uBZfSH7Itn1yFkWdMjY5BaIbnLRedUCVTTzJh9cXWFF6isNEIeuH3IQtJW8r7pSgqqJV6eieqd8M6uGX9ZWw28NJzIxkbM5HpU51f3qDoYS6804zbIaLMFDoc/KvParOUf79egmO6E3UQlT9RnN4S0JlgWZHPieenaeCohSjhXgq6jlopk+yuTmxy4yHZSuSL3a5v/ks7Z6tpYxXAcfceu9apD62Xh7Myg299g2KVIa9Vlw86LClTXxkdGOR5s6hrY7IpNtPcxuXbnB2LMjJDRQk2YtTx1dUl2VF8kdIPTAq1GRIDjH4eSDMYXNZvYlHaJNN/9jJnTdTALBXMIiIATYh7xRbQnTmoxyZT1o1v9UTC+0FnDI5yRdqxi1rjsMBG+NxOh7xYAy0HShDNTxyHElGixT8OmcwhKVf37VOUVFur2Dt4Q9Jfxv2exmBQIaysNWsgsJmXrWoN9j3uhfNbaqG1qsuXe808EgBhREh9I/SEP03BgM5Lr3mUZGQ7JynL4ZtxQKZkT4UA2Ax0P2EkTKKprQjITzM8wEsui9nOUqioHHUQEZzZ/N757jSPaNEXGhGCCBGXBhatVShDOMI8l5cLFerSHHs3hiFuEcNYGI88hpgvlIDIrv4EZgY1nIAF119fJJm/Z9nc/v0qU=
  app:
    dev: loto-lux-stage
    master: loto-lux
  on:
    repo: ranb2002/Loto-Lux
    branch:
    - dev
    - master
notifications:
  email:
    recipients:
    - Benjamin.Rancourt@USherbrooke.ca
