language: node_js
node_js:
  - 6.1.0

cache:
  directories:
    - node_modules

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
  - gulp build

script: karma start karma.conf.js --single-run

notifications:
  email:
    recipients:
    - Benjamin.Rancourt@USherbrooke.ca
