sudo: required
dist: trusty
language: node_js
node_js:
- 6.1.0
cache:
  directories:
  - node_modules
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
before_script:
- gulp build
script: karma start karma.conf.js --single-run
deploy:
  provider: heroku
  api_key:
    secure: atCB7wQawAuvB+2GMSdAas8/ebGQvRRO48gfMo7HKsoRasvl4nKwn8tdm1i3gjVbW0eaj2DfTw7i/21LIXAuENARZ0EcdY9rdgpexytngoEKoxTQBmySJctpKxBp+/Rv3nTaqGWhbI5iXc5GlQIncLKcnaFX2pJLjm8Mx3I9lDRhVY8LKllHWxpMPjPzULWTSzuAHhJtH6a7jNu+TpTpCR4uz1TpGZEQB24zjGsQRsF4MpZZek3NJxcfeFBccRlsNY+MBxfbowLyECEyXYiyk6BmeFosIUGcTWF4SalXxqtkucuek1mBrolho5Pv2uHEWl+UmflEdV3f1EQgxPSxd2dDTcYNPSF+KVBEP/TGTp2gK94VkaZlWiGDhJ7p9y0vO6NBU7QAP2aW8xSaH1AbhJku60tuj2ljdiKyHXaYB8etUZAWn/Plv/dYo1fghvw+BF/546Qpr3pYv3A28miruva/lCPFJLs8NOmnI2S6jkGZ+XP2DHNcDt7VSUGSCIFzE5/q0UchiEB70CN6rxa/n6dVU/7VYRbbm5PDMxHBvT+qST2qVg5gT+rIDHntUYOEgdj0+HBlXK0hWQ+ozCjXCSwcs5J8zIhpRMnlIVkZn8ffkIcOHBcMKeciiYZ0we9BsEoe73NXsl4QMJ+ngVGTQCKo8HbTWD+2U6XfML/ob1c=
  app:
    master: loto-lux
    dev: loto-lux-stage
  on:
    repo: ranb2002/Loto-Lux
    branch:
    - master
    - dev
notifications:
  email:
    recipients:
    - Benjamin.Rancourt@USherbrooke.ca
