language: node_js
node_js:
  - "6.1.0"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp
script: gulp

deploy:
  provider: heroku
  api_key:
    secure: "8803b38a-d16d-4e74-ad03-2ba317609113"
  app:
    master: loto-lux-stage
    production: loto-lux